apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qlink-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: qlink-server-service
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qlink-client-service
            port:
              number: 80